### ISSUE TITLE
[bug] AWS CLI not working properly in DLC

### ISSUE THREAD

**Issue by bkgardiner** [aws/deep-learning-containers#4268]
Checklist
- [X] I've prepended issue tag with type of change: [bug]
- [X] (If applicable) I've attached the script to reproduce the bug
- [X] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [X] (If applicable) I've documented below the tests I've run on the DLC image
- [X] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*
The AWS CLI is not working on the 2.1.2-neuronx-py310-sdk2.20.0-ubuntu20.04 image

*DLC image/dockerfile:*
public.ecr.aws/neuron/pytorch-inference-neuronx:2.1.2-neuronx-py310-sdk2.20.0-ubuntu20.04

*Current behavior:*
When running `aws` command the following error appears:
`ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/opt/conda/lib/python3.10/site-packages/botocore/utils.py)`

*Expected behavior:*
No errors

*Additional context:*
I've fixed the issue in the container by running:
`pip install --upgrade boto3 botocore`

**Comment by geetasg** [comment]
Thank you for reporting this issue; we will take a look.
